### ISSUE TITLE
esp01 works?

### ISSUE THREAD

**Issue by xjustbmw** [TrDA-hab/Projects#2]
very nice information regarding these servos

im trying to command few ventilation dampers using these servomotors that are quite far away from each other, so i might be using each with one module to have a good pwm signal coming to them.

Is esp8266-01 enough to control one motor ? anybody tested it ?
this is already integrated in the latest tasmota.bin ?

thanks

**Comment by xjustbmw** [comment]
https://raw.githubusercontent.com/TrDA-hab/Projects/master/Servo%2BESP8266/512.jpg
i am talking about this wiring, esp01 instead of wemos ?

**Comment by TrDA-hab** [comment]
Yes - this is already integrated in the latest tasmota.bin !
Yes - you can use esp8266-01S, I tested this.

**Comment by xjustbmw** [comment]
great stuff.I will test right away.
is it possible to send command to it (position) through mqtt ?

**Comment by TrDA-hab** [comment]
Yes, you can do it.
https://tasmota.github.io/docs/Commands/#shutterposition

**Comment by xjustbmw** [comment]
yep.just connected it on a breadboard. All seems to be working good
I did SetOption80 1 first
Then i set based on your instructions.
I have for testing a MG90S. Judders a bit when opening .. I set the open/close time for 2 seconds
Many thanks for the support.

BTW. Is the relay output a necessary setting for this to work ? 
Can 4 servos be controlled from one esp01 ?:) I dont use rx/tx for any debugging.

**Comment by xjustbmw** [comment]
20:41:42.695 RSL: stat/tasmota_784807/RESULT = {"Shutter1":{"Position":21,"Direction":0,"Target":23}}
20:41:42.699 RSL: stat/tasmota_784807/RESULT = {"ShutterPosition1":21}
one..last question. hopefully 
this is a motor deadband or software?

**Comment by TrDA-hab** [comment]
Ask all questions about software at Tasmota !!!
https://github.com/arendst/Tasmota/issues

**Comment by xjustbmw** [comment]
alright man. many thanks for your support.
have a great day
